### ISSUE TITLE
Example to run code

### ISSUE THREAD

**Issue by sumitsidana** [jacekwasilewski/RankSys-DivMF#1]
Hi @jacekwasilewski,

I am following your work of diversity based regularizer and trying to reproduce the results. It is a very interesting use of regularization to incorporate diversity in recommendation lists.

However, I have been struggling to run this code as there is no main class (entry point) anywhere.

Do you think it would be possible to share an example to run the code? A simple example to show the use of diversity based regularizer should suffice (time permitting).

Thank you very much for your time and effort involved in this.

Sumit

**Comment by jacekwasilewski** [comment]
Hi @sumitsidana,

I do not have a working snippet at this moment, but you can see how to run MFRecommender [here](https://github.com/RankSys/RankSys/blob/master/RankSys-examples/src/main/java/es/uam/eps/ir/ranksys/examples/RecommenderExample.java). Just use `DivHKVFactorizer` factorizer instead of `HKVFactorizer`. You should check other examples in RankSys to see how to create distance model (that you can cache with `CachedItemDistanceModel`). RankSys has changed a bit since this code was written, make sure that correct version is used.

Jacek.

**Comment by sumitsidana** [comment]
Hi @jacekwasilewski 

I tried with version 0.4.2 of RankSys with version 0.1 of RankSys-DivMF as dependency in RankSys (since pom of RankSys-DivMF seemed to suggest that).
But replacing `HKVFactorizer<Long, Long>(lambda, confidence, numIter).factorize(k, trainData);` with `DivHKVFactorizer<Long, Long>(lambda, alpha, dist, confidence, numIter).factorize(k, trainData);` does not seem to be working.
I get the following run time exception: 
`Exception in thread "main" java.lang.NoSuchFieldError: idx`

[stacktrace.pdf](https://github.com/jacekwasilewski/RankSys-DivMF/files/1304939/stacktrace.pdf)

I have attached the full stack trace of exception for your possible reference. 

Seems like I am missing some thing somewhere as it is not clear RankSys-DivMF is compatible with which version of RankSys. I have tried 0.4.0, 0.4.2, 0.4.3 by now and nothing seemed to have worked. Appreciate any kind of help.

Sumit

**Comment by sumitsidana** [comment]
Hi @jacekwasilewski

I managed to run the `DivRankALSFactorizer.java` correctly. For `HKVFactorizer`, I am getting `NAN` values, so something is wrong there.

**Comment by jacekwasilewski** [comment]
Hi @sumitsidana,

Sorry I did not have time to look at that. The following code (https://gist.github.com/jacekwasilewski/1f63e7703c910f0ef984840cc51eb50b) works perfectly fine for me, on MovieLens 1M dataset. You need 5 files to run it: file with a list of all users, file with a list of all items, train and test data, file with item-genre (features) pairs.
If you are still getting `NAN`s, I would check if the data you are passing is right.

**Comment by sumitsidana** [comment]
Hi @jacekwasilewski,

Thank you for providing the code.
DivRankALSFactorizer works perfectly for me as well on ML-100K. Later I will try it on ML-1M and ML-20M. I was getting `NAN`  with `HKVFactorizer` but as of now I just need `DivRankALSFactorizer` for my purpose in order to reproduce the results mentioned in the paper (Incorporating Diversity in a Learning to Rank Recommender System).
Also, I noticed with earlier versions, item-genre (features) pairs were actually item-genre-value triplets to make it work. Hope I got it right.

Thanks
Sumit

**Comment by sumitsidana** [comment]
Hi @jacekwasilewski,

Thank you very much for the code. It works perfectly on ML20M.

But the results (`precision`, `recall` and `ndcg`) I obtained slightly differ from what you have reported in your [paper](https://www.researchgate.net/publication/304817469_Incorporating_Diversity_in_a_Learning_to_Rank_Recommender_System). 

Do you remember `threshold` you had used while computing 
 metrics? I am using es.uam.eps.ir.ranksys.examples.MetricExample.java for computing the metrics and this example asks for `threshold` as the 5th parameter.

Thank you

**Comment by jacekwasilewski** [comment]
Hi @sumitsidana,
The dataset was implicitized -- 5s were transformed to 1s, and everything else to 0s. Then 1 is treated as relevant interaction. Also interactions for some items were removed, as described in the paper.

**Comment by sumitsidana** [comment]
Hi @jacekwasilewski,

I also make the data implicit exactly as you by transforming 5s to 1s and everything else to 0s but in my train and test files I keep only 1s and remove 0s. Are 0s to be kept as well? I remove items with no genres.

Also, while doing prediction there is a parameter `threshold` for metrics such as `ndcg`. I currently set it to 0.5 but changing it changes the results significantly. So, you don't use parameter `threshold` it seems?

Thanks

**Comment by jacekwasilewski** [comment]
Hi @sumitsidana,
I believe 0s should be kept as well as you want to learn to distinguish between positive and negative interactions.

Threshold tells you what rating is treated as a relevant/positive interaction in the test set.

**Comment by sumitsidana** [comment]
Hi @jacekwasilewski 

So I did that mistake of removing 0s. For threshold, it makes a lot clear after your post. I will re-run the experiments by taking into account all these changes.

Thank you very much.
